services:
  - type: web
    name: my-fastapi-app
    env: docker
    repo: https://github.com/Invincible1602/Hackofiesta
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
